Shop.Car.UI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Car.BLL;
using Shop.Car.UI.Controllers;

namespace Shop.Car.UI.Controllers
{
    public class AdminController : BaseController
    {
        UserInfoBLL UserInfoBLL = new UserInfoBLL();
        OrderInfoBLL OrderInfoBLL = new OrderInfoBLL();
        // GET: Admin
        public ActionResult Index()
        {
            ViewData.Model = UserInfoBLL.GetAllModelList(u => u.UIsAdmin == 1);
            return View();
        }


        /// <summary>
        /// 添加用户
        /// </summary>
        /// <returns></returns>
        public ActionResult AddUser()
        {
            return View();
        }

        /// <summary>
        /// 订单
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ShowOrder(int id)
        {
            ViewData.Model = OrderInfoBLL.GetAllModelList(o=>o.UId==id);
            return View();
        }


        public ActionResult DoworkOrder(int id)
        {
            if(OrderInfoBLL.DoworkOrder(id))
            {
                return Content("ok");
            }
            return Content("");
        }
    }
}

Shop.Car.UI/Controllers/BaseController.cs
using Shop.Car.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Car.UI.Controllers
{
    public class BaseController : Controller
    {

        public bool IsCheckLogin = true;

        public static UserInfo BaseUserInfo { get; set; }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);

            if(IsCheckLogin)
            {
                if(BaseUserInfo == null)
                {
                    filterContext.HttpContext.Response.Redirect("/Login/Index");
                }
            }
        }
    }
}

Shop.Car.UI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shop.Car.BLL;
using Shop.Car.Model;

namespace Shop.Car.UI.Controllers
{
    public class LoginController : BaseController
    {

        public LoginController()
        {
            IsCheckLogin = false;
        }

        UserInfoBLL userInfoBLL = new UserInfoBLL();
        public ActionResult Index()
        {
           
            return View();
        }


        public string CheckLogin(UserInfo userInfo)
        {
            UserInfo user = userInfoBLL.CheckLogin(userInfo);

            if (user == null)
            {
                return "";
            }

            BaseUserInfo = user;
            return user.UIsAdmin.ToString();
        }
    }
}

Shop.Car.UI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shop.Car.UI.Controllers
{
    public class UserController : BaseController
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
    }
}

Shop.Car.UI/Views/Admin/AddUser.cshtml
@model Shop.Car.Model.UserInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddUser</title>
</head>
<body>
    @using (Ajax.BeginForm("SubAddUser","Admin",new AjaxOptions {
		HttpMethod = "post",
		OnSuccess = "Success"
	}))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>UserInfo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UPwd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UPwd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UPwd, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.URealName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.URealName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.URealName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UIsAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UIsAdmin, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UIsAdmin, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Shop.Car.UI/Views/Admin/Index.cshtml
@model	 List<Shop.Car.Model.UserInfo>
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Index</title>
</head>
<body>
	<table>
		<tr align="center">
			<td><a href="/Admin/AddUser">新增用户</a></td>
		</tr>

		<tr>
			<th>用户ID</th>
			<th>账户</th>
			<th>真实名称</th>
			<th>操作</th>
		</tr>

		@foreach (var item in Model)
		{
		<tr>
			<td>@item.UId</td>
			<td>@item.UName</td>
			<td>@item.URealName</td>
			<td><a href="/Admin/ShowOrder/@item.UId">查看订单</a></td>

		</tr>
		}
	</table>
</body>
</html>

Shop.Car.UI/Views/Admin/ShowOrder.cshtml
@model List<Shop.Car.Model.OrderInfo>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowOrder</title>
</head>
<body>
	<table>
		<tr align="center">
			<td><a href="/Admin/AddUser">新增用户</a></td>
		</tr>

		<tr>
			<th>订单ID</th>
			<th>车名</th>
			<th>购买人</th>
			<th>数量</th>
			<th>总价</th>
			<th>购买时间</th>
			<th>备注</th>
			<th>状态</th>
			<th>操作</th>
		</tr>

		@foreach (var item in Model)
		{
			
		<tr>
			@{ string state = (item.OState == 0 ? "已下单" : "已完成"); };
			<td>@item.OId</td>
			<td>@item.CarInfo.CName</td>
			<td>@item.UserInfo.URealName</td>
			<td>@item.ONumber</td>
			<td>@item.OPrice</td>
			<td>@item.OCreateTime</td>
			<td>@item.ORemark</td>
			<td>@state</td>
			<td>
				@if (state == "已下单")
				{
					@*<a href="/Admin/DoworkOrder/@item.OId">完成订单</a>*@
					<a class="completeLink" oid="@item.OId" href="javascript">完成订单</a>
				}
			</td>


		</tr>
		}
	</table>

	<script type="text/javascript">
		$(function () {
			$('.completeLink').click(function () {
				var oid = $(this).attr('oid');
				$.post('/Admin/DoworkOrder', {id:oid}, function (res) {
					if (res == 'ok') {
						alert('成功！');
						window.location.reload();
					} else {
						alert('失败！');
					}
				});
			});
		});
	</script>
</body>
</html>

Shop.Car.UI/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Index</title>
	<script src="~/Scripts/jquery-3.3.1.min.js"></script>
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

	<script type="text/javascript">
		$(function () {
			$('from').validate({
				rules: {
					UName:{ required: true },
					UPwd: {required:true},

				},
				messages: {
					UName: { require: "用户名不能为空" },
					UPwd: { require: "密码不能为空" },
				},
			});
		});
		function Success(res) {
			if (res != "") {
				alert("登陆成功");
				if (res == '1') {

					window.location.href = '/User/Index';
				}
				else {
					window.location.href = '/Admin/Index';
				}
			}
			else {
				alert("用户名或密码错误");
			}
		}
	</script>
</head>
<body>
	@using (Ajax.BeginForm("CheckLogin", "Login", new AjaxOptions
	{
		HttpMethod = "post",
		OnSuccess = "Success"
	}))
	{
		@Html.Label("用户名:")@Html.TextBox("UName")<br/>
		@Html.Label("密  码:")@Html.TextBox("UPwd")<br />
		<input type="submit" value="提交"/>

	}
</body>
</html>

Shop.Car.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Shop.Car.UI/Views/User/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
		user
    </div>
</body>
</html>